#pragma once
#define OSGF_FX_WORLD					"world"
#define OSGF_FX_VIEW					"view"
#define OSGF_FX_PROJECTION				"projection"
#define OSGF_FX_WORLD_VIEW_PROJECTION   "gWVP"
#define OSGF_FX_MATERIAL_SPECULAR		"mtrlSpecular"
#define OSGF_FX_MATERIAL_DIFFUSE		"mtrlDiffuse"
#define OSGF_FX_MATERIAL_AMBIENT		"mtrlAmbient"
#define OSGF_FX_LIGHT_SPECULAR			"lightSpecular"
#define OSGF_FX_LIGHT_DIFFUSE			"lightDiffuse"
#define OSGF_FX_LIGHT_AMBIENT			"lightAmbient"
#define OSGF_FX_LIGHT_POSINTION			"lightPos"
#define OSGF_FX_EYE_POSITION			"eyePos"